// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwN9-pmazl8tq46T5JQwMb-OCc75clvsw',
    appId: '1:372415156547:web:c5fd92b689566ded669ff6',
    messagingSenderId: '372415156547',
    projectId: 'eventsolutions-ba453',
    authDomain: 'eventsolutions-ba453.firebaseapp.com',
    storageBucket: 'eventsolutions-ba453.firebasestorage.app',
    measurementId: 'G-G2VQMWFGDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE_rbxUdZSsLPnRSrb615uJOy_pimlE7I',
    appId: '1:372415156547:android:1989a437294af51e669ff6',
    messagingSenderId: '372415156547',
    projectId: 'eventsolutions-ba453',
    storageBucket: 'eventsolutions-ba453.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB2W-KQHVJUEX8A622rBHfYSEu6Y6Lfas',
    appId: '1:372415156547:ios:bf7798f9e8d55e38669ff6',
    messagingSenderId: '372415156547',
    projectId: 'eventsolutions-ba453',
    storageBucket: 'eventsolutions-ba453.firebasestorage.app',
    iosBundleId: 'com.example.eventsolutions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB2W-KQHVJUEX8A622rBHfYSEu6Y6Lfas',
    appId: '1:372415156547:ios:bf7798f9e8d55e38669ff6',
    messagingSenderId: '372415156547',
    projectId: 'eventsolutions-ba453',
    storageBucket: 'eventsolutions-ba453.firebasestorage.app',
    iosBundleId: 'com.example.eventsolutions',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwN9-pmazl8tq46T5JQwMb-OCc75clvsw',
    appId: '1:372415156547:web:0ac86f9df5dda27d669ff6',
    messagingSenderId: '372415156547',
    projectId: 'eventsolutions-ba453',
    authDomain: 'eventsolutions-ba453.firebaseapp.com',
    storageBucket: 'eventsolutions-ba453.firebasestorage.app',
    measurementId: 'G-QYBB6S291C',
  );
}
